<?php
/**
 * Plugin Name:       Calendar Crawl Guard
 * Plugin URI:        https://web321.co/
 * Description:       Tames the near-infinite URL space generated by event calendars (The Events Calendar and the All-in-One Event Calendar). Intercepts non-canonical calendar URLs early in the request (before the main query runs) and redirects, terminates, or feeds authority to a short list of canonical URLs — cutting crawler bandwidth and server load.
 * Version:           1.0.0
 * Requires at least: 6.0
 * Requires PHP:      8.0
 * Author:            Shawn DeWolfe, Web321 Marketing Ltd.
 * Author URI:        https://web321.co/
 * License:           GPL-2.0-or-later
 * License URI:       https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain:       calendar-crawl-guard
 *
 * @package Web321\CalendarCrawlGuard
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // No direct access.
}

define( 'CCG_VERSION', '1.0.0' );
define( 'CCG_FILE', __FILE__ );
define( 'CCG_DIR', plugin_dir_path( __FILE__ ) );
define( 'CCG_URL', plugin_dir_url( __FILE__ ) );
define( 'CCG_BASENAME', plugin_basename( __FILE__ ) );

// Option / meta keys (plugin-specific, per Web321 conventions).
define( 'CCG_OPTION', 'ccg_settings' );
define( 'CCG_DOCS_OPTION', 'ccg_docs_page_id' );
define( 'CCG_DONATE_URL', 'https://www.paypal.com/paypalme/web321co/10' );

require_once CCG_DIR . 'includes/class-ccg-docs.php';
require_once CCG_DIR . 'includes/class-ccg-activator.php';
require_once CCG_DIR . 'includes/class-ccg-settings.php';
require_once CCG_DIR . 'includes/class-ccg-logger.php';
require_once CCG_DIR . 'includes/class-ccg-provider-tec.php';
require_once CCG_DIR . 'includes/class-ccg-provider-ai1ec.php';
require_once CCG_DIR . 'includes/class-ccg-interceptor.php';
require_once CCG_DIR . 'includes/class-ccg-seo.php';

// WP-CLI commands (test / scan / providers).
if ( defined( 'WP_CLI' ) && WP_CLI ) {
	require_once CCG_DIR . 'includes/class-ccg-cli.php';
	WP_CLI::add_command( 'ccg', 'CCG_CLI' );
}

register_activation_hook( __FILE__, array( 'CCG_Activator', 'activate' ) );
register_deactivation_hook( __FILE__, array( 'CCG_Activator', 'deactivate' ) );

/**
 * Is The Events Calendar present?
 *
 * @return bool
 */
function ccg_is_tec_active(): bool {
	return class_exists( 'Tribe__Events__Main' ) || function_exists( 'tribe_get_option' );
}

/**
 * Is the All-in-One Event Calendar (Timely) present?
 *
 * @return bool
 */
function ccg_is_ai1ec_active(): bool {
	return defined( 'AI1EC_VERSION' )
		|| defined( 'AI1EC_POST_TYPE' )
		|| class_exists( 'Ai1ec_Calendar_Controller' )
		|| post_type_exists( 'ai1ec_event' );
}

/**
 * Is any supported calendar active?
 *
 * @return bool
 */
function ccg_any_calendar_active(): bool {
	return ccg_is_tec_active() || ccg_is_ai1ec_active();
}

/**
 * Events archive rewrite slug (configurable in TEC). Defaults to "events".
 *
 * @return string
 */
function ccg_events_slug(): string {
	$slug = function_exists( 'tribe_get_option' ) ? tribe_get_option( 'eventsSlug', 'events' ) : 'events';
	return sanitize_title( $slug ?: 'events' );
}

/**
 * Single-event rewrite slug (configurable in TEC). Defaults to "event".
 *
 * @return string
 */
function ccg_single_slug(): string {
	$slug = function_exists( 'tribe_get_option' ) ? tribe_get_option( 'singleEventSlug', 'event' ) : 'event';
	return sanitize_title( $slug ?: 'event' );
}

/**
 * Boot the plugin after all plugins (including TEC) have loaded.
 */
function ccg_bootstrap(): void {
	// Admin settings + plugin-list links always load so the screen is reachable.
	$settings = new CCG_Settings();
	$settings->hooks();

	// Surface a notice if no supported calendar is present — rules stay dormant.
	if ( ! ccg_any_calendar_active() ) {
		add_action(
			'admin_notices',
			static function () {
				if ( ! current_user_can( 'manage_options' ) ) {
					return;
				}
				echo '<div class="notice notice-warning"><p>';
				echo esc_html__( 'Calendar Crawl Guard is active but no supported calendar was detected. The crawl rules will not run until The Events Calendar or the All-in-One Event Calendar is installed and active.', 'calendar-crawl-guard' );
				echo '</p></div>';
			}
		);
		return;
	}

	$options = CCG_Settings::get_options();

	$interceptor = new CCG_Interceptor( $options );
	$interceptor->hooks();

	$seo = new CCG_SEO( $options, $interceptor );
	$seo->hooks();
}
add_action( 'plugins_loaded', 'ccg_bootstrap', 20 );
